services:
  mongodb:
    image: mongo:6.0.13
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express-bridgework
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongodb

  backend:
    image: bhusalashish/bridgework-backend:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/bridgework_db?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    image: bhusalashish/bridgework-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: