services:
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123

  mongo-express2:
    image: mongo-express:latest
    container_name: mongo-express2
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongodb2
    depends_on:
      - mongodb2

volumes:
  mongodb_data: