
### Get all jobs
GET http://localhost:8000/api/job
Content-Type: application/json

###

### Get a specific job by ID
GET http://localhost:8000/api/job/680d9b50de670faf3e8cf6a7
Content-Type: application/json

###

### Create a new job
POST http://localhost:8000/api/job
Content-Type: application/json

{
  "title": "Software Engineer",
  "description": "Develop and maintain software applications.",
  "location": "Remote",
  "points": 100,
  "is_active": true,
  "pay": 120000,
  "organization": "Tech Corp",
  "skills": [
    "Python",
    "FastAPI"
  ]
}

###

### Update an existing job
PUT http://localhost:8000/api/job/{{job_id}}
Content-Type: application/json

{
  "title": "Senior Software Engineer",
  "description": "Lead software development projects.",
  "location": "Remote",
  "points": 150,
  "is_active": true,
  "pay": 150000,
  "organization": "Tech Corp",
  "skills": [
    "Python",
    "FastAPI",
    "Leadership"
  ]
}

###

### Delete a job
DELETE http://localhost:8000/api/job/{{job_id}}
Content-Type: application/json

###

### Get all gig jobs
GET http://localhost:8000/api/gig
Content-Type: application/json

###

### Create a new gig job
POST http://localhost:8000/api/gig
Content-Type: application/json

{
  "title": "Freelance Writer",
  "description": "Write articles for blogs.",
  "location": "Remote",
  "points": 50,
  "is_active": true,
  "duration": "2 weeks",
  "pay": 500,
  "organization": "Content Creators Inc.",
  "skills": [
    "Writing",
    "SEO"
  ]
}

###

### Get all volunteer jobs
GET http://localhost:8000/api/volunteer
Content-Type: application/json

###

### Create a new volunteer job
POST http://localhost:8000/api/volunteer
Content-Type: application/json

{
  "title": "Community Helper",
  "description": "Assist in community events.",
  "location": "Local",
  "points": 20,
  "is_active": true,
  "pay": 120000,
  "organization": "Local Community Center",
  "skills": [
    "Event Management",
    "Communication"
  ]
}


### Create a new application
POST http://localhost:8000/api/application
Content-Type: application/json

{
  "job_id": "680d9b50de670faf3e8cf6a7",
  "applicant": "680d9b50de670faf3e8cf6a7",
  "poster": "680d9b50de670faf3e8cf6a7"
}



### get all  applications
GET http://localhost:8000/api/application?selected=true
Content-Type: application/json



### get all  applications
GET http://localhost:8000/api/application?job_id=680d9b50de670faf3e8cf6a7
Content-Type: application/json



### get one  applications
GET http://localhost:8000/api/application/680dba881e930fe215d6a3ff
Content-Type: application/json


### accpet  application
PATCH http://localhost:8000/api/application/680dba881e930fe215d6a3ff/accept
Content-Type: application/json


### reject  application
PATCH http://localhost:8000/api/application/680dba881e930fe215d6a3ff/reject
Content-Type: application/json

